# Generated by Django 4.1.7 on 2023-03-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='event',
            field=models.ManyToManyField(to='events.events'),
        ),
    ]
